<a href="https://colab.research.google.com/github/izumitempest/reconyx-framework/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hi")

Hi


We're covering
Intro to tensors


In [5]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)


2.19.0


In [7]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
# Check the number of dimensions of a tensor(ndim means number of dimensions)
scalar.ndim

0

In [11]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
vector.ndim

1

In [15]:
#Create a matrix(More than one dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [17]:
matrix.ndim

2

In [20]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [6., 9.]], dtype=tf.float16) #specify datatype with dtype
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 6.,  9.]], dtype=float16)>

In [22]:
another_matrix.ndim

2

In [24]:
#Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [26]:
tensor.ndim

3