<a href="https://colab.research.google.com/github/izumitempest/reconyx-framework/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("Hi")

Hi


We're covering
Intro to tensors


In [4]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)


2.19.0


In [5]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimensions of a tensor(ndim means number of dimensions)
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
#Create a matrix(More than one dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [6., 9.]], dtype=tf.float16) #specify datatype with dtype
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 6.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
#Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

###   Creating tensors with `tf.Variable`

In [15]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
#Change element in changeable tensor

changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Change a value in unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

### Creating random tensors
---
Random tensors are tensors of some arbitrary size which contain random numbers




**Note:** Rarely in practice will you decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

In [ ]:
# Create two random(but the same) tensors
random_1 = tf.random.Generator.from_seed(7) #set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

#Are they equal?
random_1, random_2, random_1 == random_2

### Shuffling the order of tensors


In [17]:
#Shuffle a tensor(valuable for when you want to shuffle your data so the order doesn't affect learning)

not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle our non shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [19]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Exercise:** Read through TensorFlow documentation on random seed gen: https://www/tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them

In [18]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [28]:
first_tensor = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

second_tensor = tf.constant([[10, 11],
                             [12, 13],
                             [14, 15]])

third_tensor = tf.constant([[16, 17],
                            [18, 19],
                            [20, 21],
                            [22, 23]])
fourth_tensor = tf.constant([[24, 25, 26],
                             [27, 28, 29],
                             [30, 31, 32],
                             [33, 34, 35]])

fifth_tensor = tf.constant([[36, 37, 38, 39],
                            [40, 41, 42, 43],
                            [44, 45, 46, 47],
                            [48, 49, 50, 51]])


first_tensor, second_tensor, third_tensor, fourth_tensor, fifth_tensor

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10, 11],
        [12, 13],
        [14, 15]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51]], dtype=int32)>)

In [32]:
tf.random.shuffle(first_tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [36]:
tf.random.shuffle(second_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 11],
       [14, 15],
       [12, 13]], dtype=int32)>

In [40]:
tf.random.shuffle(third_tensor)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[20, 21],
       [16, 17],
       [22, 23],
       [18, 19]], dtype=int32)>

In [45]:
tf.random.shuffle(fourth_tensor)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[24, 25, 26],
       [27, 28, 29],
       [33, 34, 35],
       [30, 31, 32]], dtype=int32)>

In [49]:
tf.random.shuffle(fifth_tensor, seed=12)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [36, 37, 38, 39]], dtype=int32)>